version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building Docker images..."
      - docker build -t hydra/static:latest ./services/static
      - docker build -t hydra/load-tester:latest ./services/load-tester
  post_build:
    commands:
      - echo "Build finished!"
