# buildspec.yml
version: 0.2

env:
  privileged: true   # <--- enables Docker-in-Docker

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build started on `date`"
      - docker --version
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building Hydra static-site image..."
      - docker build -t hydra/static ./services/static
      - echo "Building Hydra load-tester image..."
      - docker build -t hydra/load-tester ./services/load-tester
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "All images built successfully."

artifacts:
  files:
    - '**/*'
