version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build: checking environment"
      - docker --version || true
  build:
    commands:
      - echo "Running k6 load test against $TARGET_URL"
      # run k6 in a docker container; services/load-tester/k6-loadtest.js must be in repo
      - docker run --rm -i loadimpact/k6 run - < services/load-tester/k6-loadtest.js
artifacts:
  files:
    - '**/*'
