version: "3.8"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  app:
    build: ./services/app
    image: hydra/app:local
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:5000"
    restart: unless-stopped

  load-tester:
    build: ./services/load-tester
    image: hydra/load-tester:local
    depends_on:
      - app
    entrypoint: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
