apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra-app
  template:
    metadata:
      labels:
        app: hydra-app
    spec:
      containers:
        - name: app
          image: 808155925440.dkr.ecr.ap-south-1.amazonaws.com/hydra/app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hydra-app
spec:
  selector:
    app: hydra-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
